# Version
version: "3"

# services: service is `app` and build service is current directory.
services:
  app:
    build:
      context: .
    ports: 
      - "8000:8000"
      
    volumes: 
      # automatically restart docker on change, maps local folder (change) to docker folder (to update)
      - ./app:/app

    # Run command with shell
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword

    depends_on: 
      # db will start BEFORE the app service
      - db
      
  
  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword